on:
  schedule:
  - cron:  "0 0 */1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/karsanda/monorepo.git"
        source_branch: "main"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
